import './mobile-adapter.js';
import {$,esc,icon,hydrate,toast,api} from './ui.js';
import {scenes,sceneImage,sceneItems} from './scene-data.js';
import {startEditor,editorBusy,stopPreviews} from './editor.js';
import {AudioTrack,narrationSource} from './audio.js';
hydrate();
let stored={};try{stored=JSON.parse(localStorage.getItem('mammo-v1')||'{}');}catch{}if(!stored||typeof stored!=='object')stored={};
const state={positions:stored.positions||{},favorites:Array.isArray(stored.favorites)?stored.favorites:[],completed:Array.isArray(stored.completed)?stored.completed:[],answers:stored.answers||{},current:stored.current,settings:{large:false,motion:true,...stored.settings},language:['vi','en','both'].includes(stored.language)?stored.language:'both'};
let catalog=[],custom=[],currentStory=null,page=0,view='read',pageNumber=0,search='',topic='',onlyCustom=false,loadingToken=0,voiceLanguage='vi',rate=1,speaking=false,speechToken=0,installEvent,activeHotspot=null,hoverTimer;
const packs=new Map(),storyCache=new Map();const PAGE_SIZE=18;
const persist=()=>{try{localStorage.setItem('mammo-v1',JSON.stringify(state));}catch{}};
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replaceAll('đ','d').replaceAll('Đ','D').toLowerCase();
const allStories=()=>[...custom,...catalog];
const display=(vi,en)=>state.language==='en'?(en||vi):vi;
function paired(vi,en,tag='span',klass=''){return `<${tag} class="${klass}" lang="vi">${esc(vi)}</${tag}>${state.language==='both'&&en?`<${tag} class="english ${klass}" lang="en">${esc(en)}</${tag}>`:''}`;}
function applySettings(){document.body.classList.toggle('large-text',!!state.settings.large);document.body.classList.toggle('reduce-motion',!state.settings.motion);$('#language').value=state.language;}
applySettings();
function listening(active){speaking=active;$('#listen-label').textContent=active?'Dừng nghe':'Nghe kể chuyện';$('#listen [data-icon]').innerHTML=icon(active?'pause':'play');}
const narration=new AudioTrack({onState:listening,onError:()=>{toast('File giọng kể chưa phát được. Đang chuyển sang giọng thiết bị.');speakPage();}});
const music=new AudioTrack({onState:active=>{$('#music-toggle').textContent=active?'♫ Tắt nhạc':'♫ Bật nhạc nền';$('#music-toggle').setAttribute('aria-pressed',String(active));},onError:()=>toast('Chưa phát được nhạc nền. Kiểm tra mạng hoặc thử file MP3 khác.')});
function stopAllAudio(){stopSpeech();music.stop();stopPreviews();}
function speakPage(){if(!currentStory)return;const p=currentStory.pages[page];speak(voiceLanguage==='vi'?p.title+'. '+p.text:p.titleEn+'. '+p.textEn);}
function listenPage(){stopSpeech();const url=narrationSource(currentStory,page,voiceLanguage);if(url)narration.play(url,{volume:currentStory.narrationVolume??1,rate});else speakPage();}
function audioSettings(){if(!currentStory)return;if(currentStory.origin==='custom'){edit(currentStory);$('#editor-audio').scrollIntoView({block:'start'});}else modal(`<span class="modal-kicker">GIỌNG KỂ CỦA BA MẸ</span><h2 class="modal-title">Thêm âm thanh cho truyện</h2><p class="modal-text">Tạo một bản riêng của “${esc(currentStory.title)}” trong tủ sách của ba mẹ, rồi tải giọng Việt/Anh cho từng trang và nhạc nền. Bản riêng có thể sửa nội dung và hình ảnh.</p><button id="copy-for-audio" class="primary-btn">Tạo bản riêng & thêm âm thanh</button>`);}
function stopSpeech(){speechToken++;narration.stop();if('speechSynthesis'in window)speechSynthesis.cancel();speaking=false;$('#listen-label').textContent='Nghe kể chuyện';$('#listen [data-icon]').innerHTML=icon('play');document.querySelectorAll('.sentence.speaking').forEach(e=>e.classList.remove('speaking'));}
async function speak(text,language=voiceLanguage,highlight){stopSpeech();if(!('speechSynthesis'in window))return toast('Thiết bị này chưa hỗ trợ giọng đọc.');const token=speechToken;let voices=speechSynthesis.getVoices();if(!voices.length){await new Promise(r=>setTimeout(r,200));voices=speechSynthesis.getVoices();}if(token!==speechToken)return;const voice=voices.find(v=>v.lang.toLowerCase().startsWith(language));if(!voice)return toast(`Chưa có giọng ${language==='vi'?'tiếng Việt':'tiếng Anh'}. Ba mẹ thêm giọng này trong cài đặt giọng nói của thiết bị nhé.`);const utterance=new SpeechSynthesisUtterance(text);utterance.voice=voice;utterance.lang=language==='vi'?'vi-VN':'en-US';utterance.rate=.85*rate;utterance.onstart=()=>{if(token!==speechToken)return;speaking=true;$('#listen-label').textContent='Dừng nghe';$('#listen [data-icon]').innerHTML=icon('pause');highlight?.classList.add('speaking');};utterance.onend=()=>{if(token===speechToken)stopSpeech();};utterance.onerror=e=>{if(token!==speechToken)return;stopSpeech();if(!['interrupted','canceled'].includes(e.error))toast('Chưa phát được giọng đọc. Vui lòng thử lại.');};speechSynthesis.speak(utterance);}
async function getStory(meta){if(storyCache.has(meta.id))return storyCache.get(meta.id);if(meta.origin==='custom'){const s=await api('/api/stories/'+meta.id);storyCache.set(s.id,s);return s;}if(!packs.has(meta.pack)){const response=await fetch(meta.pack);if(!response.ok)throw Error('Chưa tải được truyện. Kiểm tra mạng rồi thử lại nhé.');const data=await response.json();packs.set(meta.pack,data);data.forEach(s=>storyCache.set(s.id,s));}const s=storyCache.get(meta.id);if(!s)throw Error('Không tìm thấy nội dung truyện.');return s;}
async function openStory(id){const token=++loadingToken;stopAllAudio();const meta=allStories().find(s=>s.id===id);if(!meta)return toast('Chưa tìm thấy câu chuyện này.');$('#toast').classList.remove('visible');try{const s=await getStory(meta);if(token!==loadingToken)return;currentStory=s;page=Math.max(0,Math.min(s.pages.length-1,Number(state.positions[id])||0));showView('read');render();window.scrollTo({top:0,behavior:state.settings.motion?'smooth':'instant'});}catch(e){toast(e.message);}}
function render(){if(!currentStory)return;const s=currentStory,p=s.pages[page],last=page===s.pages.length-1;$('#music-toggle').hidden=!s.music;$('#audio-source').textContent=narrationSource(s,page,voiceLanguage)?'Giọng kể đã tải lên':'Giọng đọc thiết bị';$('#story-title').innerHTML=state.language==='both'?`${esc(p.title)}<span class="title-english" lang="en">${esc(p.titleEn)}</span>`:esc(display(p.title,p.titleEn));
 const vi=p.text.split('\n').filter(Boolean),en=p.textEn.split('\n').filter(Boolean);$('#story-text').innerHTML=Array.from({length:Math.max(vi.length,en.length)},(_,i)=>`<div class="sentence-pair">${state.language!=='en'&&vi[i]?`<button class="sentence" lang="vi" data-sentence="${i}" data-sentence-lang="vi" title="Chạm để nghe câu tiếng Việt">${esc(vi[i])}</button>`:''}${state.language!=='vi'&&en[i]?`<button class="sentence english" lang="en" data-sentence="${i}" data-sentence-lang="en" title="Tap to hear the English sentence">${esc(en[i])}</button>`:''}</div>`).join('');
 $('#chapter').textContent=`${state.language==='en'?'PAGE':'TRANG'} ${String(page+1).padStart(2,'0')} · ${display(s.theme,s.themeEn).toUpperCase()}`;$('#theme-tag').textContent=display(s.theme,s.themeEn);$('#story-length').textContent=`${s.pages.length} trang`;$('#left-page').textContent=String(page+1).padStart(2,'0');$('#page-count').innerHTML=`${state.language==='en'?'Page':'Trang'} ${page+1} <span>/ ${s.pages.length}</span>`;$('#prev').disabled=page===0;$('#next').innerHTML=icon(last?'star':'arrow-right');$('#next').setAttribute('aria-label',last?'Hoàn thành câu chuyện':'Trang tiếp');$('#dots').innerHTML=s.pages.map((_,i)=>`<button data-page="${i}" class="${i===page?'active':''}" aria-label="Trang ${i+1}" ${i===page?'aria-current="page"':''}></button>`).join('');$('#bookmark').setAttribute('aria-pressed',String(state.favorites.includes(s.id)));$('#bookmark').setAttribute('aria-label',state.favorites.includes(s.id)?'Bỏ lưu truyện':'Lưu truyện');$('#vocab').hidden=!p.word;$('#vocab-label').textContent=`${p.word} · ${p.wordEn}`;
 $('#scene').src=sceneImage(p);$('#scene').alt=p.image?display(p.title,p.titleEn):display(scenes[p.scene].vi,scenes[p.scene].en);$('#scene-caption').textContent=display(p.caption,p.captionEn);$('#scene-popover').hidden=true;activeHotspot=null;const hotspots=itemsFor(p);$('#scene-hotspots').innerHTML=hotspots.map((h,i)=>`<button class="object-region" data-object="${i}" style="z-index:${hotspots.length-i};left:${Math.max(0,h.x-h.w/2)}%;top:${Math.max(0,h.y-h.h/2)}%;width:${Math.min(h.w,100-Math.max(0,h.x-h.w/2))}%;height:${Math.min(h.h,100-Math.max(0,h.y-h.h/2))}%" aria-label="${esc(h.vi+' · '+h.en)}"><span class="object-dot" aria-hidden="true">+</span></button>`).join('');$('#mascot').hidden=!!p.image;$('.reading-note p').textContent=display(s.prompt,s.promptEn);$('.stage-bottom>span:first-child').textContent=`✦ ${display(s.theme,s.themeEn)} · Chạm câu chữ để nghe`;const index=catalog.findIndex(c=>c.id===s.id);const upcoming=catalog[(index+1)%catalog.length];$('#more-stories strong').innerHTML=esc(display(upcoming.title,upcoming.titleEn))+' '+icon('arrow-right');$('#more-stories').dataset.next=upcoming.id;$('#activity').hidden=!s.question;state.current=s.id;state.positions[s.id]=page;persist();}
function itemsFor(p){return [...(p.hotspots||[]),...(p.image?[]:sceneItems(p))].sort((a,b)=>a.w*a.h-b.w*b.h);}
function showObject(i,read=false){if(!currentStory)return;const h=itemsFor(currentStory.pages[page])[i];if(!h)return;activeHotspot=h;$('#scene-popover').hidden=false;$('#scene-popover').innerHTML=`<button id="hide-object" aria-label="Đóng nội dung" class="popover-close">×</button><strong>${esc(h.vi)} <span lang="en">${esc(h.en)}</span></strong><p>${esc(h.detail||'')}</p><p class="english" lang="en">${esc(h.detailEn||'')}</p><div><button data-object-read="vi">▶ Tiếng Việt</button><button data-object-read="en">▶ English</button></div>`;if(read)speak(voiceLanguage==='vi'?h.vi+'. '+h.detail:h.en+'. '+h.detailEn);}
function changePage(n){if(!currentStory||n<0||n>=currentStory.pages.length)return;stopSpeech();page=n;render();$('#book').classList.remove('turning');void $('#book').offsetWidth;$('#book').classList.add('turning');}
function card(s){return `<article class="book-card"><button class="card-open" data-story="${esc(s.id)}"><div class="cover-wrap"><img src="${esc(s.coverImage||'/assets/'+s.cover+'.webp')}" alt="" width="600" height="400" loading="lazy"><span class="cover-tag">${s.origin==='custom'?'CỦA BA MẸ':'VI / EN'}</span></div><div class="book-card-content"><small>${esc(display(s.theme,s.themeEn))} · ${s.pageCount} trang</small><h2>${esc(display(s.title,s.titleEn))}</h2>${state.language==='both'?`<p class="card-title-en" lang="en">${esc(s.titleEn)}</p>`:''}<p>${esc(display(s.description,s.descriptionEn))}</p><div class="card-action"><span>${state.completed.includes(s.id)?'Đọc lại':Number(state.positions[s.id])>0?'Đọc tiếp':'Mở câu chuyện'}</span>${icon('arrow-right')}</div></div></button>${s.origin==='custom'?`<div class="card-edit"><button data-edit="${esc(s.id)}">Sửa truyện</button><button data-delete="${esc(s.id)}">Xóa</button></div>`:''}</article>`;}
function filtered(){const pool=onlyCustom?custom:allStories(),q=normalize(search);return pool.filter(s=>(!topic||s.theme===topic)&&(!q||normalize(`${s.title} ${s.titleEn} ${s.theme} ${s.themeEn}`).includes(q)));}
function renderLibrary(){const list=filtered(),max=Math.max(1,Math.ceil(list.length/PAGE_SIZE));pageNumber=Math.min(pageNumber,max-1);$('#result-count').textContent=`${list.length} truyện · ${catalog.length} có sẵn + ${custom.length} của ba mẹ`;$('#book-grid').innerHTML=list.slice(pageNumber*PAGE_SIZE,(pageNumber+1)*PAGE_SIZE).map(card).join('')||'<div class="empty-state">Chưa có truyện phù hợp. Thử từ khác hoặc thêm câu chuyện của riêng mình.</div>';$('#catalog-pagination').innerHTML=`<button class="secondary-btn" id="catalog-prev" ${pageNumber===0?'disabled':''}>← Trước</button><span>Trang ${pageNumber+1} / ${max}</span><button class="secondary-btn" id="catalog-next" ${pageNumber>=max-1?'disabled':''}>Tiếp →</button>`;}
function topics(){const values=[...new Set(allStories().map(s=>s.theme))];$('#topic-filter').innerHTML='<option value="">Tất cả chủ đề</option>'+values.map(t=>`<option value="${esc(t)}" ${t===topic?'selected':''}>${esc(t)}</option>`).join('');}
function renderGarden(){$('#garden').innerHTML=`<div class="garden-stat"><strong>✦ ${state.completed.length}</strong><span>Truyện đã hoàn thành</span></div><div class="garden-stat"><strong>${Object.keys(state.answers).length}</strong><span>Điều hay đã khám phá</span></div><div class="garden-stat"><strong>${state.favorites.length}</strong><span>Sách yêu thích</span></div>`;$('#saved-grid').innerHTML=allStories().filter(s=>state.favorites.includes(s.id)).map(card).join('')||'<div class="empty-state">Chạm vào dấu trang trên sách để giữ lại truyện yêu thích.<button id="empty-library">Khám phá tủ sách</button></div>';}
function showView(v){stopAllAudio();view=v;for(const name of ['reading','library','collection','editor'])$('#'+name+'-view').hidden=(name==='reading'?'read':name)!==v;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='library')renderLibrary();if(v==='collection')renderGarden();}
function modal(content){stopAllAudio();$('#modal-content').innerHTML=content;if(!$('#modal').open)$('#modal').showModal();}
function finish(){if(!state.completed.includes(currentStory.id)){state.completed.push(currentStory.id);persist();}modal(`<span class="modal-kicker">✦ WELL DONE · BÉ GIỎI LẮM</span><h2 class="modal-title">Một câu chuyện đã nở hoa!</h2><p class="modal-text">${esc(currentStory.title)}</p><p class="english">${esc(currentStory.titleEn)}</p><p class="modal-text">${esc(display(currentStory.prompt,currentStory.promptEn))}</p>${currentStory.question?'<button id="finish-quiz" class="primary-btn">Khám phá điều hay</button>':''}<button id="finish-library" class="secondary-btn">Về tủ sách</button>`);}
function quiz(){const s=currentStory;if(!s.question)return;modal(`<span class="modal-kicker">CÙNG BÉ NGHĨ · LET’S THINK</span><h2 class="modal-title">${esc(display(s.question,s.questionEn))}</h2>${state.language==='both'?`<p class="english">${esc(s.questionEn)}</p>`:''}<div class="answers">${s.answers.map((a,i)=>`<button class="answer" data-answer="${i}">${esc(display(a,s.answersEn[i]))}${state.language==='both'?`<small lang="en">${esc(s.answersEn[i])}</small>`:''}</button>`).join('')}</div><p class="feedback" id="feedback" role="status"></p>`);}
function parent(){modal(`<span class="modal-kicker">GÓC CỦA BA MẸ</span><h2 class="modal-title">Đọc cùng, lớn cùng</h2><label class="setting">Chữ truyện lớn hơn<input id="large-text" type="checkbox" ${state.settings.large?'checked':''}></label><label class="setting">Hiệu ứng 3D & chuyển động<input id="motion" type="checkbox" ${state.settings.motion?'checked':''}></label><p class="modal-text">Chọn Việt + English để xem bản dịch ngay dưới mỗi đoạn. Chạm câu chữ để nghe đúng ngôn ngữ, hoặc đổi nút VI / EN cạnh nút nghe.</p><button id="parent-create" class="primary-btn">+ Thêm truyện của ba mẹ</button><h3>Giọng kể & nhạc nền</h3><p class="modal-text">Ba mẹ có thể tải file ghi âm Việt/Anh theo từng trang, thêm nhạc nền và chỉnh âm lượng trong màn hình sửa truyện.</p>${currentStory?'<button id="parent-audio" class="secondary-btn">Cấu hình âm thanh truyện đang đọc</button>':''}<h3>Cài trên điện thoại</h3><p class="modal-text">iPhone: Safari → Chia sẻ → Thêm vào Màn hình chính.<br>Android: Chrome → Cài đặt ứng dụng hoặc Thêm vào Màn hình chính.</p>${installEvent?'<button id="install" class="secondary-btn">Cài Mầm Mơ</button>':''}<p class="modal-text">Truyện, ảnh và âm thanh ba mẹ thêm được lưu trên thiết bị này. Tiến độ đọc và sách yêu thích vẫn lưu trên thiết bị này. Giọng đọc tùy giọng Việt/Anh đã cài trên máy. Truyện có sẵn đã mở có thể đọc lại khi mất mạng.</p>`);}
async function loadCustom(){try{const data=await api('/api/stories');custom=data.stories;$('#custom-status').textContent='';topics();if(view==='library')renderLibrary();if(view==='collection')renderGarden();}catch(e){$('#custom-status').innerHTML=`<span>${esc(e.message)}</span><button id="retry-custom">Thử lại</button>`;}}
function edit(s=null){showView('editor');startEditor(s,{cancel:()=>showView('library'),saved:async saved=>{storyCache.set(saved.id,saved);await loadCustom();currentStory=saved;page=0;showView('read');render();}});}
document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;if(view==='editor'&&editorBusy()){e.preventDefault();return toast('Đợi tệp hoặc truyện lưu xong nhé.');}if(b.matches('.brand')){e.preventDefault();showView('library');}if(b.dataset.view){if(b.dataset.view==='read'&&!currentStory)return;showView(b.dataset.view);}if(b.dataset.story)await openStory(b.dataset.story);if(b.dataset.edit){try{edit(await getStory(custom.find(s=>s.id===b.dataset.edit)));}catch(e){toast(e.message);}}if(b.dataset.delete){const s=custom.find(s=>s.id===b.dataset.delete);modal(`<h2 class="modal-title">Xóa câu chuyện này?</h2><p class="modal-text">${esc(s.title)}</p><button class="secondary-btn" id="close-modal-action">Giữ lại</button><button class="primary-btn danger" id="confirm-delete" data-id="${esc(s.id)}">Xóa truyện</button>`);}if(b.dataset.page!==undefined)changePage(Number(b.dataset.page));if(b.dataset.object!==undefined)showObject(Number(b.dataset.object));if(b.dataset.objectRead&&activeHotspot)speak(b.dataset.objectRead==='vi'?activeHotspot.vi+'. '+activeHotspot.detail:activeHotspot.en+'. '+activeHotspot.detailEn,b.dataset.objectRead);if(b.dataset.sentence!==undefined){const lang=b.dataset.sentenceLang;const text=(lang==='vi'?currentStory.pages[page].text:currentStory.pages[page].textEn).split('\n').filter(Boolean)[Number(b.dataset.sentence)];speak(text,lang,b);}if(b.dataset.answer!==undefined){const n=Number(b.dataset.answer),s=currentStory;if(n===s.correct){state.answers[s.id]=true;persist();$('#feedback').textContent=display(s.feedback,s.feedbackEn);if(state.language==='both')$('#feedback').innerHTML=esc(s.feedback)+'<br><span lang="en">'+esc(s.feedbackEn)+'</span>';document.querySelectorAll('.answer').forEach(a=>a.disabled=true);b.classList.add('selected');}else{b.disabled=true;$('#feedback').textContent=state.language==='en'?'Let’s think about what helped the friends in the story.':'Bé thử nghĩ xem điều gì đã giúp các bạn trong câu chuyện nhé.';}}
 switch(b.id){
 case'back-library':case'empty-library':showView('library');break;
 case'prev':changePage(page-1);break;case'next':page===currentStory.pages.length-1?finish():changePage(page+1);break;
 case'bookmark':state.favorites=state.favorites.includes(currentStory.id)?state.favorites.filter(x=>x!==currentStory.id):[...state.favorites,currentStory.id];persist();render();toast('Đã cập nhật sách yêu thích.');break;
 case'listen':if(!currentStory)break;if(speaking)stopSpeech();else listenPage();break;
 case'audio-settings':audioSettings();break;
 case'parent-audio':$('#modal').close();audioSettings();break;
 case'copy-for-audio':{const copy=structuredClone(currentStory);delete copy.id;delete copy.revision;copy.origin='custom';copy.title=copy.title.slice(0,140)+' · Bản của ba mẹ';copy.titleEn=copy.titleEn.slice(0,140)+' · Family edition';$('#modal').close();edit(copy);$('#editor-audio').scrollIntoView({block:'start'});break;}
 case'music-toggle':if(music.active)music.stop();else if(currentStory?.music)music.play(currentStory.music,{volume:currentStory.musicVolume??.15,loop:true});break;
 case'speed':rate=rate===1?.8:rate===.8?1.2:1;$('#speed').textContent=rate+'×';stopSpeech();break;
 case'voice-language':voiceLanguage=voiceLanguage==='vi'?'en':'vi';$('#voice-language').textContent=voiceLanguage.toUpperCase();stopSpeech();render();break;
 case'vocab':{const p=currentStory.pages[page];modal(`<span class="modal-kicker">MỘT TỪ MỚI · A NEW WORD</span><h2 class="modal-title">${esc(p.word)}<span class="title-english" lang="en">${esc(p.wordEn)}</span></h2><p class="modal-text">${esc(p.meaning)}</p><p class="english" lang="en">${esc(p.meaningEn)}</p><button id="word-vi" class="secondary-btn">▶ Tiếng Việt</button><button id="word-en" class="secondary-btn">▶ English</button>`);break;}
 case'word-vi':speak(currentStory.pages[page].word+'. '+currentStory.pages[page].meaning,'vi');break;case'word-en':speak(currentStory.pages[page].wordEn+'. '+currentStory.pages[page].meaningEn,'en');break;
 case'activity':case'finish-quiz':quiz();break;case'parent':parent();break;
 case'close-modal':case'close-modal-action':$('#modal').close();break;case'finish-library':$('#modal').close();showView('library');break;
 case'more-stories':await openStory(b.dataset.next);break;
 case'fullscreen':try{if(document.fullscreenElement)await document.exitFullscreen();else if($('#reading-stage').requestFullscreen)await $('#reading-stage').requestFullscreen();else toast('Xoay ngang điện thoại để xem sách rộng hơn nhé.');}catch{toast('Thiết bị này chưa mở được toàn màn hình.');}break;
 case'install':if(installEvent){await installEvent.prompt();installEvent=null;$('#modal').close();}break;
 case'hide-object':$('#scene-popover').hidden=true;break;
 case'mascot':b.classList.remove('celebrate');void b.offsetWidth;b.classList.add('celebrate');modal('<span class="modal-kicker">CHÀO BÉ! · HELLO!</span><h2 class="modal-title">Mình là Milo!</h2><p class="modal-text">Mình thích nghe những ý tưởng mới của bé. Hôm nay bé muốn kể chuyện gì?</p><p class="english" lang="en">I love hearing your new ideas. What story would you like to tell today?</p><button id="close-modal-action" class="primary-btn">Đọc tiếp · Keep reading</button>');break;
 case'new-story':edit();break;case'parent-create':$('#modal').close();edit();break;
 case'catalog-prev':pageNumber--;renderLibrary();$('#library-view').scrollIntoView();break;case'catalog-next':pageNumber++;renderLibrary();$('#library-view').scrollIntoView();break;
 case'retry-custom':await loadCustom();break;
 case'confirm-delete':{b.disabled=true;try{await api('/api/stories/'+b.dataset.id,{method:'DELETE'});storyCache.delete(b.dataset.id);state.favorites=state.favorites.filter(x=>x!==b.dataset.id);persist();$('#modal').close();await loadCustom();if(currentStory?.id===b.dataset.id)await openStory(catalog[0].id);toast('Đã xóa truyện.');}catch(error){toast(error.message);b.disabled=false;}break;}
 }
});
$('#story-search').addEventListener('input',e=>{search=e.target.value;pageNumber=0;renderLibrary();});$('#topic-filter').addEventListener('change',e=>{topic=e.target.value;pageNumber=0;renderLibrary();});$('#custom-only').addEventListener('change',e=>{onlyCustom=e.target.checked;pageNumber=0;renderLibrary();});
$('#language').addEventListener('change',e=>{state.language=e.target.value;if(state.language!=='both'){voiceLanguage=state.language;$('#voice-language').textContent=voiceLanguage.toUpperCase();}persist();stopSpeech();render();});
document.addEventListener('change',e=>{if(e.target.id==='large-text')state.settings.large=e.target.checked;else if(e.target.id==='motion')state.settings.motion=e.target.checked;else return;applySettings();persist();});
$('#modal').addEventListener('close',stopSpeech);$('#modal').addEventListener('click',e=>{if(e.target!==$('#modal'))return;const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#modal').close();});
document.addEventListener('keydown',e=>{if(view!=='read'||!currentStory||$('#modal').open||e.target.closest('input,textarea,select'))return;if(e.key==='Escape')$('#scene-popover').hidden=true;if(e.key==='ArrowRight'){e.preventDefault();page===currentStory.pages.length-1?finish():changePage(page+1);}if(e.key==='ArrowLeft'){e.preventDefault();changePage(page-1);}});
let touch;$('#book').addEventListener('touchstart',e=>{touch=[e.changedTouches[0].clientX,e.changedTouches[0].clientY];},{passive:true});$('#book').addEventListener('touchend',e=>{if(!touch||e.target.closest('button')||!currentStory)return;const dx=e.changedTouches[0].clientX-touch[0],dy=e.changedTouches[0].clientY-touch[1];if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5)changePage(page+(dx<0?1:-1));touch=null;},{passive:true});
const tilt=$('#scene-tilt');let frame;tilt.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse'||!state.settings.motion||matchMedia('(prefers-reduced-motion: reduce)').matches)return;cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const r=tilt.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;tilt.style.setProperty('--rx',`${-y*7}deg`);tilt.style.setProperty('--ry',`${x*9}deg`);});});tilt.addEventListener('pointerleave',()=>{cancelAnimationFrame(frame);tilt.style.setProperty('--rx','0deg');tilt.style.setProperty('--ry','0deg');});
$('#scene-hotspots').addEventListener('pointerover',e=>{if(e.pointerType!=='mouse')return;const b=e.target.closest('[data-object]');if(b){clearTimeout(hoverTimer);hoverTimer=setTimeout(()=>showObject(Number(b.dataset.object)),180);}});$('#scene-hotspots').addEventListener('pointerout',()=>clearTimeout(hoverTimer));$('#scene-hotspots').addEventListener('focusin',e=>{if(e.target.dataset.object!==undefined)showObject(Number(e.target.dataset.object));});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAllAudio();});window.addEventListener('pagehide',stopAllAudio);
$('#story-text').textContent='Đang mở tủ sách…';$('#prev').disabled=true;$('#next').disabled=true;
try{const response=await fetch('/data/catalog.json');if(!response.ok)throw Error();catalog=await response.json();topics();$('#next').disabled=false;await openStory(catalog.find(s=>s.id===state.current)?.id||catalog[0].id);loadCustom();}catch{$('#story-text').innerHTML='Chưa tải được tủ sách. <button class="secondary-btn" id="reload-app">Thử lại</button>';$('#reload-app')?.addEventListener('click',()=>location.reload());}


window.addEventListener('mammo-pause',stopAllAudio);
