plugins { id 'com.android.application' }
android {
 namespace 'com.mammo.reader'
 compileSdk 35
 defaultConfig { applicationId 'com.mammo.reader'; minSdk 23; targetSdk 35; versionCode 3; versionName '3.0.0' }
 compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}
